name: Tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly, v0.11.4, v0.10.0]

    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
            
      - name: Setup test dependencies
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/ci/opt
          ln -s "$PWD" ~/.local/share/nvim/site/pack/ci/opt/vhdl-utils.nvim
          cd ~/.local/share/nvim/site/pack/ci/opt
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim 
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter.git
      
      - name: Install VHDL parser
        run: |
          nvim --headless +"lua require('nvim-treesitter.install').update({ with_sync = true })({ 'vhdl' })" +quit
      
      - name: Run tests
        run: |
          nvim --headless -u tests/minimal_init.lua \
            -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/minimal_init.lua'}"
